function y = f(p_guess,exhaust1,exhaust2,exhaust3,strcoeff1,strcoeff2,strcoeff3,deltav)
y = (exhaust1*log((1+p_guess*exhaust1)/(p_guess*exhaust1*strcoeff1))) + ...
    (exhaust2*log((1+p_guess*exhaust2)/(p_guess*exhaust2*strcoeff2))) + ...
    (exhaust3*log((1+p_guess*exhaust3)/(p_guess*exhaust3*strcoeff3))) - deltav;
end
